### ISSUE TITLE
Decide on when and where we would like to do "official" benchmark runs.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-benchmark#12]
The official benchmarks runs are those that are saved to S3 and viewable on qutip.org/qutip-bencmark. Some examples we have discussed:

- On each commit to dev.major (i.e. v5) on the qutip repository.
- Nightly on qutip-benchmark against dev.major

We might also want to do some historical runs, e.g.:

- A historical run against all merge commits from the last year of qutip/master (i.e. v4).

These historical runs we can implement later though.

**Comment by xspronken** [comment]
I believe this was sorted in #10, when we separated the workflows into 2, one for the nightly benchmarks and one to test new commits and PRs.
