### ISSUE TITLE
Consider changing the default benchmark timer.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-benchmark#14]
pytest-benchmark allows changing the default benchmark timer, for example, for the FAQ:

> I can’t avoid using VMs or running other programs. What can I do?
>    As a last ditch effort pytest-benchmark allows you to plugin in custom timers (--benchmark-timer). You could use something like time.process_time (Python 3.3+ only) as the timer. Process time [doesn’t include sleeping or waiting for I/O](https://en.wikipedia.org/wiki/CPU_time).

-- see https://pytest-benchmark.readthedocs.io/en/latest/faq.html

Maybe `process_time` is not the best for some benchmarks, but it is an interesting option for removing variability on VMs, and perhaps it would even be possible to record both somehow.

**Comment by hodgestar** [comment]
It would be nice to run some tests on GitHub action runners to see how stable this makes the result (and thus whether it's worth the trade-off).

**Comment by xspronken** [comment]
Tests were made and process_time did not perform better than the default timer.
In the images below the timer was changed from process_time to the default timer on 2022-08-31.
We can not see any major changes in reliability and certain datatypes, notably the qutip ones perform faster.
![Matmul_op@op-512-dense](https://user-images.githubusercontent.com/60646093/188892768-b23217eb-a98e-4be5-b0d4-7f7bb36f0491.png)
![Matmul_op@op-512-sparse](https://user-images.githubusercontent.com/60646093/188893220-18c421b5-c158-418b-b016-3deeacfbe1e6.png)
![Add-512-sparse](https://user-images.githubusercontent.com/60646093/188893280-e31c5f19-b5ea-47b7-90a0-7a7ba60fb9f8.png)

![mesolve-128](https://user-images.githubusercontent.com/60646093/188893379-c29ea166-d270-4fdb-ab0d-29331d953425.png)
