### ISSUE TITLE
Add links to benchmark website in Qutip.org

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-benchmark#36]
Add links to benchmark website in Qutip.org. I guess this could be opened as an issue also on qutip.github.io, and the PR would go there, but wanted to make sure this is flagged also here. 

I think we could add benchmarks to the top horizontal menu in qutip.org, e.g., just like "News" and other items.

A possible change in this repository could be having the top left "QuTiP" button take one to qutip.org.

**Comment by hodgestar** [comment]
Added!
